api_platform:
    defaults:
        pagination_items_per_page: 10
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    error_formats:
        jsonproblem: ['application/problem+json']
