
vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /public/images
            upload_destination: '%kernel.project_dir%/public/images'
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 1, dirs: 2 }