
vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 20 }
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 1, dirs: 2 }
