version: "3.6"
services:
################################## php-fpm
  film_backend:
    container_name: php_film
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      XDEBUG_SESSION: "docker-server"
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  film_nginx:
    container_name: nginx_film
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: library/mysql:5.7
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    ports:
      - "3307:3306"
################################## pma
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
    ports:
      - "3128:80"

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379

volumes:
  mysql-data:
  mysql-log:

